# Generated by Django 4.1.3 on 2023-10-05 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UserSignup',
        ),
    ]
