# Generated by Django 4.1.3 on 2023-10-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_users_usersignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
