# Generated by Django 4.1.3 on 2023-10-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
